### ISSUE TITLE
no available  or write for SoftwareSerial

### ISSUE THREAD

**Issue by jvcleave** [Arachnid/sm130#1]
I get the following errors when trying to compile

adapters.cpp: In member function 'virtual void UARTInterfaceAdapter::send(nfc_command_t, uint8_t*, int)':
adapters.cpp:20: error: 'class SoftwareSerial' has no member named 'write'
adapters.cpp:21: error: 'class SoftwareSerial' has no member named 'write'
adapters.cpp:22: error: 'class SoftwareSerial' has no member named 'write'
adapters.cpp:23: error: 'class SoftwareSerial' has no member named 'write'
adapters.cpp:26: error: 'class SoftwareSerial' has no member named 'write'
adapters.cpp:28: error: 'class SoftwareSerial' has no member named 'write'
adapters.cpp: In member function 'virtual uint8_t UARTInterfaceAdapter::available()':
adapters.cpp:32: error: 'class SoftwareSerial' has no member named 'available'

any ideas? thanks for this

**Comment by jvcleave** [comment]
After seeing the comment response on your blog I replaced SoftwareSerial with NewSoftSerial (http://arduiniana.org/libraries/newsoftserial/)

I did have to make NewSoftSerial.write public (I expect to have to do some changes here) but I was at least able to compile

**Comment by Arachnid** [comment]
You need to use Beta version 11, from here, which already has that member public: http://arduiniana.org/2011/01/newsoftserial-11-beta/

**Comment by jvcleave** [comment]
ah - it was renamed to SoftwareSerial as well - now i get it

thanks!
